version: '2'
services:
  db:
    image: mariadb:10.1
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: randomepassword
      MYSQL_DATABASE: webwork
      MYSQL_USER: webworkWrite
      MYSQL_PASSWORD: passwordRW
  app:
    build: .
    image: webwork_dokuwiki_ubuntu_16
    depends_on:
      - db
      - r
    volumes:
      - ".:/opt/webwork/webwork2"

      # OLD approach put the courses tree under webwork2/.data/courses
      #- "./.data/courses:/opt/webwork/courses"
      # NEW appoach puts the courses tree in a separate tree outside of webwork2/
      - "../ww-docker-data/courses:/opt/webwork/courses"

      # Uncomment the line below to use local OPL for development
      - "../opl:/opt/webwork/libraries/webwork-open-problem-library"
      # Uncomment the line below to use local PG for development
      - "../pg:/opt/webwork/pg"
      #
      # For DokuWiki
      - "/home/tani/DW/faq:/var/www/html/faq"
      - "/home/tani/DW/faq_english:/var/www/html/faq_english"
      - "/home/tani/DW/staff:/var/www/html/staff"
      - "/home/tani/DW/test.html:/var/www/html/test.html"
      #
      # SSL certificates
      #
      - "/home/tani/WW/2016:/etc/ssl/2016"
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      DEV: 0
  r:
    image: ubcctlt/rserve
    ports:
      - "6311:6311"

volumes:
  mysql:

